### ISSUE TITLE
Nomeclatura dos arquivos das reuniões

### ISSUE THREAD

**Issue by vanessametonini** [MariaLabHackerspace/grupo-estudos-programacao#1]
Praticamente um desafio para nosso próximo encontro.

Temos que começar organizar no nosso repositório o histórico das coisas que falamos e vamos aprendendo nos encontros. Pensei em criar um arquivo como: "encontro-01" e ir linkando com a agenda no readme.

Porém como nosso próximo encontro é sobre nomenclaturas, acredito ser legal usarmos essa situação para aplicar o que aprendemos :)

**Comment by kathianihei** [comment]
Poderia criar um arquivo como "primeiroEncontro" ou "primeiro_encontro". Eu, particularmente não gosto de utilizar o "_", prefiro o estilo Camel Case :)

**Comment by vanessametonini** [comment]
Definido usarmos lower camel case, com os nomes dos arquivos sobre o assunto falado no encontro.
